nulfierHash = "0x0fb849f7cf35865c838cef48782e803b2c38263e2f467799c87eff168eb4d897"
nullifier = "0x075bcd15"
proofPathIndicies = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
proofSiblings = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
root = "0x2af910e9112bb352483e49e7034aecc42d274c284073db156ffd2e4e37e67c75"
secret = ""
